const state = {
  studentName: "",
  studentClass: "",
  totalScore: 0,
  currentLevel: 0,
  unlockedLevel: 1,
  rank: "見習員",
  badges: [],
  achievements: [],
  levelScores: { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0 },
  l1Index: 0,
  l1Answered: false,
  l2Found: [],
  l2Selected: null,
  l2Answered: false,
  l3Index: 0,
  l3TimeLeft: 75,
  l3Timer: null,
  l3Answered: false,
  l4MissionIndex: 0,
  l4InvestigationsLeft: 3,
  l4SelectedRestaurant: null,
  l4Completed: [],
  l4PendingNews: null,
  l5Index: 0,
  l5TimeLeft: 135,
  l5Timer: null,
  l5Answered: false,
  questionStartTime: 0,
  speedTimer: null
};

